### ISSUE TITLE
Flow deployment failed (Request ID: ...)

### ISSUE THREAD

**Issue by big-thousand** [jina-ai/jcloud#86]
#### Command
```bash
jina hub push ./XXXOperator
```

Error when
```
⠧ Cloud building ... buildWorkspace: progress (STEP 4/4 RUN pip install --default-timeout=1000 --compile --no-cache-dir      -r 
requirements.txt)
```

requirements.txt
```
argostranslate
jina
docarray
# sentence-transformers
# lingua-language-detector
torch
numpy
transformers
optimum[onnxruntime-gpu]
optimumEasyNMT
```

#### Flow yaml
```yaml
# Paste your Flow yaml here
```

#### Flow ID / Request ID
```text
Flow ID: N/A
Request ID: N/A
```

---

#### `.env` file

N/A 

#### `jina` version
```bash
jina -vf
...
```

#### Logs

N/A
```
⠋ Pushing `./TextOperator/` ...🔐 You are not logged in to Jina AI. To log in, use jina auth login or set env variable JINA_AUTH_TOKEN.

Failed on building Docker image. Potential solutions:
  - If you haven't provide a Dockerfile in the executor bundle, you may want to provide one,
    as the auto-generated one on the cloud did not work.
  - If you have provided a Dockerfile, you may want to check the validity of this Dockerfile.

Please report this session_id: [yellow bold]87cb21c4-4fc4-11ed-b4c5-02125e52ee48[/] to https://github.com/jina-ai/jina/issues
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/3.8.13/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/jina_cli/api.py", line 182, in hub
    getattr(HubIO(args), args.hub_cli)()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/hubble/executor/hubio.py", line 661, in push
    raise e
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/hubble/executor/hubio.py", line 642, in push
    self._sync_push(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/hubble/executor/hubio.py", line 467, in _sync_push
    raise Exception(
Exception: 
Failed on building Docker image. Potential solutions:
  - If you haven't provide a Dockerfile in the executor bundle, you may want to provide one,
    as the auto-generated one on the cloud did not work.
  - If you have provided a Dockerfile, you may want to check the validity of this Dockerfile.
 session_id: 87cb21c4-4fc4-11ed-b4c5-02125e52ee48
```
---

**Comment by deepankarm** [comment]
@big-thousand Can you please share your Flow yaml so we can verify the deployment?
